version: 2.1
commands:
  install_civicrm:
    description: "Install CiviCRM"
    parameters:
      build_name:
        type: string
        default: master
      type:
        type: string
        default: drupal-clean
      version:
        type: string
        default: master
      url:
        type: string
        default: http://localhost:8080
    steps:
      - run: su - buildkit -c "/buildkit/bin/civibuild create << parameters.build_name >> --civi-ver << parameters.version >> --type << parameters.type >> --url << parameters.url >>"
  install_extension:
    description: "Install Extension"
    parameters:
      build_name:
        type: string
        default: master
    steps:
      - run: |
          cp /root/project /buildkit/build/<< parameters.build_name >>/sites/default/files/civicrm/ext/$CIRCLE_PROJECT_REPONAME -r
          chown buildkit:buildkit /buildkit/build/<< parameters.build_name >>/sites/default/files/civicrm/ext/$CIRCLE_PROJECT_REPONAME -R
          su - buildkit -c "cd /buildkit/build/<< parameters.build_name >> && cv en $CIRCLE_PROJECT_REPONAME"
  run_civilint:
    description: "Run civilint"
    parameters:
      build_name:
        type: string
        default: master
    steps:
      - run: su - buildkit -c "cd /buildkit/build/<< parameters.build_name >>/sites/default/files/civicrm/ext/$CIRCLE_PROJECT_REPONAME && civilint *"
  run_phpunit:
    description: "Run PHPUnit"
    parameters:
      build_name:
        type: string
        default: master
    steps:
      - run: su - buildkit -c "cd /buildkit/build/<< parameters.build_name >>/sites/default/files/civicrm/ext/$CIRCLE_PROJECT_REPONAME && phpunit5"
  run_all:
    description: "Run all steps"
    parameters:
      build_name:
        type: string
        default: master
      type:
        type: string
        default: drupal-clean
      version:
        type: string
        default: master
      url:
        type: string
        default: http://localhost:8080
    steps:
      - install_civicrm:
          build_name: << parameters.build_name >>
          type: << parameters.type >>
          version: << parameters.version >>
          url: << parameters.url >>
      - install_extension:
          build_name: << parameters.build_name >>
      - run_civilint:
          build_name: << parameters.build_name >>
      - run_phpunit:
          build_name: << parameters.build_name >>

executors:
  civicrm:
    docker:
      - image: michaelmcandrew/civicrm-buildkit
        name: civicrm
        environment:
          TERM: xterm-color
          APACHE_RUN_USER: buildkit
      - image: mysql:5.7
        name: mysql
        environment:
          MYSQL_ROOT_PASSWORD: buildkit

jobs:
  build_mysql_5_7:
    executor: civicrm
    steps:
      - checkout
      - run_all
      - run_all:
          build_name: civi-5.13
          version: "5.13"
          url: http://localhost:8082
  build_mysql_8:
    executor: civicrm
    docker:
      - image: michaelmcandrew/civicrm-buildkit
        name: civicrm
        environment:
          TERM: xterm-color
          APACHE_RUN_USER: buildkit
      - image: mysql:8
        name: mysql
        environment:
          MYSQL_ROOT_PASSWORD: buildkit
    steps:
      - checkout
      - run_all
      - run_all:
          build_name: civi-5.13
          version: "5.13"
          url: http://localhost:8082
  build_mariadb_10_2:
    executor: civicrm
    docker:
      - image: michaelmcandrew/civicrm-buildkit
        name: civicrm
        environment:
          TERM: xterm-color
          APACHE_RUN_USER: buildkit
      - image: mariadb:10.2
        name: mysql
        environment:
          MYSQL_ROOT_PASSWORD: buildkit
    steps:
      - checkout
      - run_all
      - run_all:
          build_name: civi-5.13
          version: "5.13"
          url: http://localhost:8082
  build_mariadb_10_3:
    executor: civicrm
    docker:
      - image: michaelmcandrew/civicrm-buildkit
        name: civicrm
        environment:
          TERM: xterm-color
          APACHE_RUN_USER: buildkit
      - image: mariadb:10.3
        name: mysql
        environment:
          MYSQL_ROOT_PASSWORD: buildkit
    steps:
      - checkout
      - run_all
      - run_all:
          build_name: civi-5.13
          version: "5.13"
          url: http://localhost:8082

workflows:
  version: 2
  build:
    jobs:
      - build_mysql_5_7
      - build_mysql_8
      - build_mariadb_10_2
      - build_mariadb_10_3