<?php

use CRM_Advancedlogtables_ExtensionUtil as E;

return [
  'advancedlogtables_storage_engine' => [
    'group_name' => 'domain',
    'name' => 'advancedlogtables_storage_engine',
    'type' => 'String',
    'default' => 'InnoDB',
    'quick_form_type' => 'Element',
    'html_type' => 'text',
    'add' => '4.7',
    'title' => E::ts('Storage engine'),
    'description' => E::ts('Storage engine to use for log tables. Use <code>SHOW ENGINES</code> to get a list of supported storage engines.<br>Default: <code>InnoDB</code>'),
    'is_domain' => 1,
    'is_contact' => 0,
    'settings_pages' => ['advancedlogtables' => ['weight' => 1]],
  ],
  'advancedlogtables_storage_engine_config' => [
    'group_name' => 'domain',
    'name' => 'advancedlogtables_storage_engine_config',
    'type' => 'String',
    'default' => 'ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=4',
    'quick_form_type' => 'Element',
    'html_type' => 'text',
    'add' => '4.7',
    'title' => E::ts('Advanced Storage engine configuration'),
    'description' => E::ts('Advanced storage engine configuration for log tables.<br>Default: <code>ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=4</code>'),
    'is_domain' => 1,
    'is_contact' => 0,
    'settings_pages' => ['advancedlogtables' => ['weight' => 2]],
  ],
  'advancedlogtables_index_contact' => [
    'group_name' => 'domain',
    'name' => 'advancedlogtables_index_contact',
    'type' => 'Boolean',
    'default' => TRUE,
    'quick_form_type' => 'YesNo',
    'html_type' => 'radio',
    'add' => '4.7',
    'title' => E::ts('Create contact indexes'),
    'description' => E::ts('Create an index for every column referencing <code>civicrm_contact</code>.<br>Default: <em>Yes</em>'),
    'is_domain' => 1,
    'is_contact' => 0,
    'settings_pages' => ['advancedlogtables' => ['weight' => 3]],
  ],
  'advancedlogtables_index_conn_id' => [
    'group_name' => 'domain',
    'name' => 'advancedlogtables_index_conn_id',
    'type' => 'Boolean',
    'default' => TRUE,
    'quick_form_type' => 'YesNo',
    'html_type' => 'radio',
    'add' => '4.7',
    'title' => E::ts('Create connection ID indexes'),
    'description' => E::ts('Create an index for column <code>log_conn_id</code>.<br>Default: <em>Yes</em>'),
    'is_domain' => 1,
    'is_contact' => 0,
    'settings_pages' => ['advancedlogtables' => ['weight' => 4]],
  ],
  'advancedlogtables_index_log_date' => [
    'group_name' => 'domain',
    'name' => 'advancedlogtables_index_log_date',
    'type' => 'Boolean',
    'default' => TRUE,
    'quick_form_type' => 'YesNo',
    'html_type' => 'radio',
    'add' => '4.7',
    'title' => E::ts('Create log date indexes'),
    'description' => E::ts('Create an index for column <code>log_date</code>.<br>Default: <em>Yes</em>'),
    'is_domain' => 1,
    'is_contact' => 0,
    'settings_pages' => ['advancedlogtables' => ['weight' => 5]],
  ],
  'advancedlogtables_index_id' => [
    'group_name' => 'domain',
    'name' => 'advancedlogtables_index_id',
    'type' => 'Boolean',
    'default' => TRUE,
    'quick_form_type' => 'YesNo',
    'html_type' => 'radio',
    'add' => '4.7',
    'title' => E::ts('Create ID indexes'),
    'description' => E::ts('Create an index for column <code>id</code>.<br>Default: <em>Yes</em>'),
    'is_domain' => 1,
    'is_contact' => 0,
    'settings_pages' => ['advancedlogtables' => ['weight' => 6]],
  ],
  'advancedlogtables_excludetables' => [
    'group_name' => 'domain',
    'name' => 'advancedlogtables_excludetables',
    'type' => 'String',
    'default' => TRUE,
    'quick_form_type' => 'Select',
    'html_type' => 'select',
    'add' => '4.7',
    'title' => E::ts('Tables for exclusion'),
    'description' => E::ts('Tables to exclude from logging'),
    'is_domain' => 1,
    'is_contact' => 0,
    'settings_pages' => ['advancedlogtables' => ['weight' => 7]],
  ],
  'advancedlogtables_negate_exclusion' => [
    'group_name' => 'domain',
    'name' => 'advancedlogtables_negate_exclusion',
    'type' => 'Boolean',
    'default' => TRUE,
    'quick_form_type' => 'YesNo',
    'html_type' => 'radio',
    'add' => '4.7',
    'title' => E::ts('Negate exclusion'),
    'description' => E::ts('Turns exclusion into inclusion'),
    'is_domain' => 1,
    'is_contact' => 0,
    'settings_pages' => ['advancedlogtables' => ['weight' => 8]],
  ],
];
